name: dad_jokes_flutter
description: Can i has a dad joke plz?

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # presentation
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5
  responsive_sizer: ^3.1.1
  google_fonts: ^3.0.1
  auto_route: ^5.0.1

  # application
  flutter_bloc: ^8.1.1

  # data
  dio: ^4.0.6

  # injection
  injectable: ^1.5.3
  get_it: ^7.2.0

  # dto and annotation
  # Freezed is stuck to 2.1.0+1 because auto_route_generator depends on old version of analyzer
  freezed: 2.1.0+1
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0
  json_serializable: ^6.1.4
  dartz: ^0.10.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.0
  auto_route_generator: ^5.0.2
  injectable_generator: ^1.5.4
  lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/smile.svg
